name: ubuntu-latest

on:
  push:
    branches: [ m**, sd/* ]
    paths: ['src/**', 'test/**', '.github/**','!README.md' ]
  pull_request:
    branches: [ m** ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Bash tests
      run: bash -xv ./test/test.bash
